package model;
// Generated 2016-1-19 11:52:40 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name="resources"
    ,catalog="test"
    , uniqueConstraints = @UniqueConstraint(columnNames="resource_name") 
)
public class Resources  implements java.io.Serializable {


     private Integer id;
     private String resourceName;
     private String resourceType;
     private String resourceContent;
     private String resourceDesc;
     private Integer enabled;

    public Resources() {
    }

	
    public Resources(String resourceName, String resourceType, String resourceContent, String resourceDesc) {
        this.resourceName = resourceName;
        this.resourceType = resourceType;
        this.resourceContent = resourceContent;
        this.resourceDesc = resourceDesc;
    }
    public Resources(String resourceName, String resourceType, String resourceContent, String resourceDesc, Integer enabled) {
       this.resourceName = resourceName;
       this.resourceType = resourceType;
       this.resourceContent = resourceContent;
       this.resourceDesc = resourceDesc;
       this.enabled = enabled;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="resource_name", unique=true, nullable=false, length=100)
    public String getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }
    
    @Column(name="resource_type", nullable=false, length=100)
    public String getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }
    
    @Column(name="resource_content", nullable=false, length=200)
    public String getResourceContent() {
        return this.resourceContent;
    }
    
    public void setResourceContent(String resourceContent) {
        this.resourceContent = resourceContent;
    }
    
    @Column(name="resource_desc", nullable=false, length=200)
    public String getResourceDesc() {
        return this.resourceDesc;
    }
    
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc;
    }
    
    @Column(name="enabled")
    public Integer getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }




}


