package model;
// Generated 2016-1-19 11:52:40 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="s_menu"
    ,catalog="test"
)
public class SMenu  implements java.io.Serializable {


     private int id;
     private String name;
     private String url;
     private Integer parentId;
     private Integer sort;
     private Integer sysId;

    public SMenu() {
    }

	
    public SMenu(int id) {
        this.id = id;
    }
    public SMenu(int id, String name, String url, Integer parentId, Integer sort, Integer sysId) {
       this.id = id;
       this.name = name;
       this.url = url;
       this.parentId = parentId;
       this.sort = sort;
       this.sysId = sysId;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="url", length=60)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="parent_id")
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="sort")
    public Integer getSort() {
        return this.sort;
    }
    
    public void setSort(Integer sort) {
        this.sort = sort;
    }
    
    @Column(name="sys_id")
    public Integer getSysId() {
        return this.sysId;
    }
    
    public void setSysId(Integer sysId) {
        this.sysId = sysId;
    }




}


