package model;
// Generated 2016-1-19 11:52:40 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="test"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Integer enabled;
     private Integer expired;
     private Integer locked;
     private String mobile;
     private String fullName;
     private Date lastLoginTime;
     private Integer loginErrorCount;
     private Date createTime;
     private String fullname;
     private Set authoritieses = new HashSet(0);

    public Users() {
    }

    public Users(String username, String password, Integer enabled, Integer expired, Integer locked, String mobile, String fullName, Date lastLoginTime, Integer loginErrorCount, Date createTime, String fullname, Set authoritieses) {
       this.username = username;
       this.password = password;
       this.enabled = enabled;
       this.expired = expired;
       this.locked = locked;
       this.mobile = mobile;
       this.fullName = fullName;
       this.lastLoginTime = lastLoginTime;
       this.loginErrorCount = loginErrorCount;
       this.createTime = createTime;
       this.fullname = fullname;
       this.authoritieses = authoritieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="username", length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="enabled")
    public Integer getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
    
    @Column(name="expired")
    public Integer getExpired() {
        return this.expired;
    }
    
    public void setExpired(Integer expired) {
        this.expired = expired;
    }
    
    @Column(name="locked")
    public Integer getLocked() {
        return this.locked;
    }
    
    public void setLocked(Integer locked) {
        this.locked = locked;
    }
    
    @Column(name="mobile", length=11)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="full_name", length=45)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login_time", length=19)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    
    @Column(name="login_error_count")
    public Integer getLoginErrorCount() {
        return this.loginErrorCount;
    }
    
    public void setLoginErrorCount(Integer loginErrorCount) {
        this.loginErrorCount = loginErrorCount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="fullname", length=45)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set getAuthoritieses() {
        return this.authoritieses;
    }
    
    public void setAuthoritieses(Set authoritieses) {
        this.authoritieses = authoritieses;
    }




}


